### ISSUE TITLE
Typo in instructions

### ISSUE THREAD

**Issue by morrowwm** [klausj1/homeassistant-statistics#23]
### System Health details

Just a documentation issue.

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/klausj1/homeassistant-statistics/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Thank you for creating this integration, it is very useful.

README.md says:

> Or statistics for not existing sensors (external statistics). These sensors have a ':' in its name, e.g. sensor.not_existing_sun_solar_azimuth

which should be

> Or statistics for not existing sensors (external statistics). These sensors have a ':' in its name, e.g. sensor:not_existing_sun_solar_azimuth

?

### Reproduction steps

1. Read the instructions.
2.
3.
...

### Debug logs

```text
Just a documentation issue.
```

### Diagnostics dump

Just a documentation issue.

**Comment by klausj1** [comment]
Fixed.
