### ISSUE TITLE
Add Location History support 

### ISSUE THREAD

**Issue by wes1993** [klausj1/homeassistant-statistics#33]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/klausj1/homeassistant-statistics/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Add option to import Location History from a CSV file, below the information to be imported:
Latitude, Longitude, Date

### Describe alternatives you've considered

No alternative solution found.

### Additional context

No

**Comment by klausj1** [comment]
I never worked with a location entity. Is it possible to show the existing history of a location entity in a graph? I am wondering how the location is stored in the database, can you please check and provide the information?

**Comment by klausj1** [comment]
No feedback since two months, closing issue
