### ISSUE TITLE
Is there any way to enter data for the 'statistics_short_term` table?

### ISSUE THREAD

**Issue by puterboy** [klausj1/homeassistant-statistics#52]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/klausj1/homeassistant-statistics/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I would like to import short term statistics (i.e., once every 5 minutes) as well as the hourly statistics that your integration currently covers.

### Describe the solution you'd like

Similar code with ability to upload a file with short term statistics data to be entered into the `statistics_short_term` table.
(Ideally, also a REST API so json encoded short term statistics could be added via an API rather than uploading a file)

### Describe alternatives you've considered

Manually adding stuff to the SQLite database or purging the recorder.

### Additional context

-

**Comment by klausj1** [comment]
I am not aware of an HA-interface I could use for this. I would need a method similar to async_import_statistics / async_add_external_statistics which also works for short term statistics. If you find that out, I could give it a try.

**Comment by klausj1** [comment]
No feedback, close.
