### ISSUE TITLE
minor bug in setting "source"

### ISSUE THREAD

**Issue by schmidtnz** [klausj1/homeassistant-statistics#60]
### Describe the issue

Minor bug in `custom_components/import_statistics/__init__.py`:

Line 81 (`source = statistic_id.split(".")[0]`), which is under the `elif` block on line 80, will never be able to split by "." as any `statistic_id` values with "." will have matched the `if` block on line 78 (`if "." in statistic_id:`).

Likely this should read something like
`source = statistic_id.split(":")[0]`

Sorry, I'm not 100% confident what the intent is here, otherwise I would have created a PR with this change.

**Comment by klausj1** [comment]
Which version are you referring to? The source of 1.0.1 is here: https://github.com/klausj1/homeassistant-statistics/blob/1.0.1/custom_components/import_statistics/__init__.py. Please add a link to the sourcefile here.

**Comment by schmidtnz** [comment]
Hi Klaus, apologies - I was looking at the source of what was downloaded through HA and had not seen that there was a newer version on github. I can see this has been fixed in the current 1.0.1 version.
