### ISSUE TITLE
start value does not allow minute other than 00

### ISSUE THREAD

**Issue by jkyngan** [klausj1/homeassistant-statistics#9]
### System Health details

\`

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/klausj1/homeassistant-statistics/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Failed to call service import_statistics.import_from_file. Invalid timestamp

### Reproduction steps

statistic_id	sum	start	state	unit
sensor.electricity_consumption	0.731	21.02.2024 00:01	5962.22	Kwh

### Debug logs

```text
\`
```

**Comment by klausj1** [comment]
This integration imports long term statistics. Therefore, the timestamps must be an exact hour.

**Comment by klausj1** [comment]
Closing the issue
